-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity logistic_regression_Loop_read_input_features_proc2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of logistic_regression_Loop_read_input_features_proc2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln27_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal i_fu_104 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_fu_262_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal features_V_fu_108 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_32_fu_272_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_fu_276_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal features_V_1_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_2_fu_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_3_fu_120 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_4_fu_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_5_fu_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_6_fu_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_7_fu_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_8_fu_140 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_9_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_10_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_11_fu_152 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_12_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_13_fu_160 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_14_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_15_fu_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_16_fu_172 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_17_fu_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_18_fu_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_19_fu_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_20_fu_188 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_21_fu_192 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_22_fu_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_23_fu_200 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_24_fu_204 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_25_fu_208 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_26_fu_212 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_27_fu_216 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_28_fu_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_29_fu_224 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_30_fu_228 : STD_LOGIC_VECTOR (7 downto 0);
    signal features_V_31_fu_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_8_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_9_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_10_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_11_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_12_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_13_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_14_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_15_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_16_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_17_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_18_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_19_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_20_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_21_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_22_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_23_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_24_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_25_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_26_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_27_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_28_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_29_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_30_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_return_31_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_condition_2632 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component logistic_regression_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component logistic_regression_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component logistic_regression_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_in_stream_V_data_V_U : component logistic_regression_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component logistic_regression_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component logistic_regression_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component logistic_regression_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_0_preg <= features_V_31_fu_232;
                end if; 
            end if;
        end if;
    end process;


    ap_return_10_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_10_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_10_preg <= features_V_21_fu_192;
                end if; 
            end if;
        end if;
    end process;


    ap_return_11_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_11_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_11_preg <= features_V_20_fu_188;
                end if; 
            end if;
        end if;
    end process;


    ap_return_12_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_12_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_12_preg <= features_V_19_fu_184;
                end if; 
            end if;
        end if;
    end process;


    ap_return_13_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_13_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_13_preg <= features_V_18_fu_180;
                end if; 
            end if;
        end if;
    end process;


    ap_return_14_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_14_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_14_preg <= features_V_17_fu_176;
                end if; 
            end if;
        end if;
    end process;


    ap_return_15_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_15_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_15_preg <= features_V_16_fu_172;
                end if; 
            end if;
        end if;
    end process;


    ap_return_16_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_16_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_16_preg <= features_V_15_fu_168;
                end if; 
            end if;
        end if;
    end process;


    ap_return_17_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_17_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_17_preg <= features_V_14_fu_164;
                end if; 
            end if;
        end if;
    end process;


    ap_return_18_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_18_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_18_preg <= features_V_13_fu_160;
                end if; 
            end if;
        end if;
    end process;


    ap_return_19_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_19_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_19_preg <= features_V_12_fu_156;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_1_preg <= features_V_30_fu_228;
                end if; 
            end if;
        end if;
    end process;


    ap_return_20_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_20_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_20_preg <= features_V_11_fu_152;
                end if; 
            end if;
        end if;
    end process;


    ap_return_21_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_21_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_21_preg <= features_V_10_fu_148;
                end if; 
            end if;
        end if;
    end process;


    ap_return_22_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_22_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_22_preg <= features_V_9_fu_144;
                end if; 
            end if;
        end if;
    end process;


    ap_return_23_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_23_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_23_preg <= features_V_8_fu_140;
                end if; 
            end if;
        end if;
    end process;


    ap_return_24_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_24_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_24_preg <= features_V_7_fu_136;
                end if; 
            end if;
        end if;
    end process;


    ap_return_25_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_25_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_25_preg <= features_V_6_fu_132;
                end if; 
            end if;
        end if;
    end process;


    ap_return_26_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_26_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_26_preg <= features_V_5_fu_128;
                end if; 
            end if;
        end if;
    end process;


    ap_return_27_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_27_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_27_preg <= features_V_4_fu_124;
                end if; 
            end if;
        end if;
    end process;


    ap_return_28_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_28_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_28_preg <= features_V_3_fu_120;
                end if; 
            end if;
        end if;
    end process;


    ap_return_29_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_29_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_29_preg <= features_V_2_fu_116;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_2_preg <= features_V_29_fu_224;
                end if; 
            end if;
        end if;
    end process;


    ap_return_30_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_30_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_30_preg <= features_V_1_fu_112;
                end if; 
            end if;
        end if;
    end process;


    ap_return_31_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_31_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_31_preg <= features_V_fu_108;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_3_preg <= features_V_28_fu_220;
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_4_preg <= features_V_27_fu_216;
                end if; 
            end if;
        end if;
    end process;


    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_5_preg <= features_V_26_fu_212;
                end if; 
            end if;
        end if;
    end process;


    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_6_preg <= features_V_25_fu_208;
                end if; 
            end if;
        end if;
    end process;


    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_7_preg <= features_V_24_fu_204;
                end if; 
            end if;
        end if;
    end process;


    ap_return_8_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_8_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_8_preg <= features_V_23_fu_200;
                end if; 
            end if;
        end if;
    end process;


    ap_return_9_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_9_preg <= ap_const_lv8_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_9_preg <= features_V_22_fu_196;
                end if; 
            end if;
        end if;
    end process;


    i_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_2632)) then
                if ((icmp_ln27_fu_256_p2 = ap_const_lv1_0)) then 
                    i_fu_104 <= add_ln27_fu_262_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_104 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_A) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_10_fu_148 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_B) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_11_fu_152 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_C) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_12_fu_156 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_D) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_13_fu_160 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_E) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_14_fu_164 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_F) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_15_fu_168 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_10) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_16_fu_172 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_11) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_17_fu_176 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_12) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_18_fu_180 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_13) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_19_fu_184 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_1_fu_112 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_14) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_20_fu_188 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_15) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_21_fu_192 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_16) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_22_fu_196 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_17) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_23_fu_200 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_18) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_24_fu_204 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_19) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_25_fu_208 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1A) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_26_fu_212 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1B) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_27_fu_216 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1C) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_28_fu_220 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1D) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_29_fu_224 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_2) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_2_fu_116 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1E) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_30_fu_228 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_1F) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_31_fu_232 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_3) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_3_fu_120 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_4) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_4_fu_124 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_5) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_5_fu_128 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_6) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_6_fu_132 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_7) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_7_fu_136 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_8) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_8_fu_140 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_9) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_9_fu_144 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (trunc_ln30_fu_276_p1 = ap_const_lv5_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                features_V_fu_108 <= features_V_32_fu_272_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln27_fu_262_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_2632_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
                ap_condition_2632 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_loop_exit_ready, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_31_fu_232, ap_return_0_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_0 <= features_V_31_fu_232;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_30_fu_228, ap_return_1_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_1 <= features_V_30_fu_228;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_10_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_21_fu_192, ap_return_10_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_10 <= features_V_21_fu_192;
        else 
            ap_return_10 <= ap_return_10_preg;
        end if; 
    end process;


    ap_return_11_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_20_fu_188, ap_return_11_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_11 <= features_V_20_fu_188;
        else 
            ap_return_11 <= ap_return_11_preg;
        end if; 
    end process;


    ap_return_12_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_19_fu_184, ap_return_12_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_12 <= features_V_19_fu_184;
        else 
            ap_return_12 <= ap_return_12_preg;
        end if; 
    end process;


    ap_return_13_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_18_fu_180, ap_return_13_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_13 <= features_V_18_fu_180;
        else 
            ap_return_13 <= ap_return_13_preg;
        end if; 
    end process;


    ap_return_14_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_17_fu_176, ap_return_14_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_14 <= features_V_17_fu_176;
        else 
            ap_return_14 <= ap_return_14_preg;
        end if; 
    end process;


    ap_return_15_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_16_fu_172, ap_return_15_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_15 <= features_V_16_fu_172;
        else 
            ap_return_15 <= ap_return_15_preg;
        end if; 
    end process;


    ap_return_16_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_15_fu_168, ap_return_16_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_16 <= features_V_15_fu_168;
        else 
            ap_return_16 <= ap_return_16_preg;
        end if; 
    end process;


    ap_return_17_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_14_fu_164, ap_return_17_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_17 <= features_V_14_fu_164;
        else 
            ap_return_17 <= ap_return_17_preg;
        end if; 
    end process;


    ap_return_18_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_13_fu_160, ap_return_18_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_18 <= features_V_13_fu_160;
        else 
            ap_return_18 <= ap_return_18_preg;
        end if; 
    end process;


    ap_return_19_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_12_fu_156, ap_return_19_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_19 <= features_V_12_fu_156;
        else 
            ap_return_19 <= ap_return_19_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_29_fu_224, ap_return_2_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_2 <= features_V_29_fu_224;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_20_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_11_fu_152, ap_return_20_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_20 <= features_V_11_fu_152;
        else 
            ap_return_20 <= ap_return_20_preg;
        end if; 
    end process;


    ap_return_21_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_10_fu_148, ap_return_21_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_21 <= features_V_10_fu_148;
        else 
            ap_return_21 <= ap_return_21_preg;
        end if; 
    end process;


    ap_return_22_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_9_fu_144, ap_return_22_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_22 <= features_V_9_fu_144;
        else 
            ap_return_22 <= ap_return_22_preg;
        end if; 
    end process;


    ap_return_23_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_8_fu_140, ap_return_23_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_23 <= features_V_8_fu_140;
        else 
            ap_return_23 <= ap_return_23_preg;
        end if; 
    end process;


    ap_return_24_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_7_fu_136, ap_return_24_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_24 <= features_V_7_fu_136;
        else 
            ap_return_24 <= ap_return_24_preg;
        end if; 
    end process;


    ap_return_25_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_6_fu_132, ap_return_25_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_25 <= features_V_6_fu_132;
        else 
            ap_return_25 <= ap_return_25_preg;
        end if; 
    end process;


    ap_return_26_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_5_fu_128, ap_return_26_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_26 <= features_V_5_fu_128;
        else 
            ap_return_26 <= ap_return_26_preg;
        end if; 
    end process;


    ap_return_27_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_4_fu_124, ap_return_27_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_27 <= features_V_4_fu_124;
        else 
            ap_return_27 <= ap_return_27_preg;
        end if; 
    end process;


    ap_return_28_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_3_fu_120, ap_return_28_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_28 <= features_V_3_fu_120;
        else 
            ap_return_28 <= ap_return_28_preg;
        end if; 
    end process;


    ap_return_29_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_2_fu_116, ap_return_29_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_29 <= features_V_2_fu_116;
        else 
            ap_return_29 <= ap_return_29_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_28_fu_220, ap_return_3_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_3 <= features_V_28_fu_220;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_30_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_1_fu_112, ap_return_30_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_30 <= features_V_1_fu_112;
        else 
            ap_return_30 <= ap_return_30_preg;
        end if; 
    end process;


    ap_return_31_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_fu_108, ap_return_31_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_31 <= features_V_fu_108;
        else 
            ap_return_31 <= ap_return_31_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_27_fu_216, ap_return_4_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_4 <= features_V_27_fu_216;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_26_fu_212, ap_return_5_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_5 <= features_V_26_fu_212;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_25_fu_208, ap_return_6_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_6 <= features_V_25_fu_208;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    ap_return_7_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_24_fu_204, ap_return_7_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_7 <= features_V_24_fu_204;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    ap_return_8_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_23_fu_200, ap_return_8_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_8 <= features_V_23_fu_200;
        else 
            ap_return_8 <= ap_return_8_preg;
        end if; 
    end process;


    ap_return_9_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, features_V_22_fu_196, ap_return_9_preg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_9 <= features_V_22_fu_196;
        else 
            ap_return_9 <= ap_return_9_preg;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_state1, i_fu_104, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_104;
        end if; 
    end process;

    features_V_32_fu_272_p1 <= in_stream_TDATA_int_regslice(8 - 1 downto 0);
    icmp_ln27_fu_256_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv6_20) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, icmp_ln27_fu_256_p2, ap_done_reg, ap_start_int, in_stream_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start_int = ap_const_logic_0) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0)))) and (icmp_ln27_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln30_fu_276_p1 <= ap_sig_allocacmp_i_1(5 - 1 downto 0);
end behav;
