// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module logistic_regression_Loop_read_input_features_proc2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
output  [7:0] ap_return_16;
output  [7:0] ap_return_17;
output  [7:0] ap_return_18;
output  [7:0] ap_return_19;
output  [7:0] ap_return_20;
output  [7:0] ap_return_21;
output  [7:0] ap_return_22;
output  [7:0] ap_return_23;
output  [7:0] ap_return_24;
output  [7:0] ap_return_25;
output  [7:0] ap_return_26;
output  [7:0] ap_return_27;
output  [7:0] ap_return_28;
output  [7:0] ap_return_29;
output  [7:0] ap_return_30;
output  [7:0] ap_return_31;

reg ap_idle;
reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;
reg[7:0] ap_return_4;
reg[7:0] ap_return_5;
reg[7:0] ap_return_6;
reg[7:0] ap_return_7;
reg[7:0] ap_return_8;
reg[7:0] ap_return_9;
reg[7:0] ap_return_10;
reg[7:0] ap_return_11;
reg[7:0] ap_return_12;
reg[7:0] ap_return_13;
reg[7:0] ap_return_14;
reg[7:0] ap_return_15;
reg[7:0] ap_return_16;
reg[7:0] ap_return_17;
reg[7:0] ap_return_18;
reg[7:0] ap_return_19;
reg[7:0] ap_return_20;
reg[7:0] ap_return_21;
reg[7:0] ap_return_22;
reg[7:0] ap_return_23;
reg[7:0] ap_return_24;
reg[7:0] ap_return_25;
reg[7:0] ap_return_26;
reg[7:0] ap_return_27;
reg[7:0] ap_return_28;
reg[7:0] ap_return_29;
reg[7:0] ap_return_30;
reg[7:0] ap_return_31;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln27_fu_256_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
reg   [5:0] i_fu_104;
wire   [5:0] add_ln27_fu_262_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_1;
reg   [7:0] features_V_fu_108;
wire   [7:0] features_V_32_fu_272_p1;
wire   [4:0] trunc_ln30_fu_276_p1;
reg   [7:0] features_V_1_fu_112;
reg   [7:0] features_V_2_fu_116;
reg   [7:0] features_V_3_fu_120;
reg   [7:0] features_V_4_fu_124;
reg   [7:0] features_V_5_fu_128;
reg   [7:0] features_V_6_fu_132;
reg   [7:0] features_V_7_fu_136;
reg   [7:0] features_V_8_fu_140;
reg   [7:0] features_V_9_fu_144;
reg   [7:0] features_V_10_fu_148;
reg   [7:0] features_V_11_fu_152;
reg   [7:0] features_V_12_fu_156;
reg   [7:0] features_V_13_fu_160;
reg   [7:0] features_V_14_fu_164;
reg   [7:0] features_V_15_fu_168;
reg   [7:0] features_V_16_fu_172;
reg   [7:0] features_V_17_fu_176;
reg   [7:0] features_V_18_fu_180;
reg   [7:0] features_V_19_fu_184;
reg   [7:0] features_V_20_fu_188;
reg   [7:0] features_V_21_fu_192;
reg   [7:0] features_V_22_fu_196;
reg   [7:0] features_V_23_fu_200;
reg   [7:0] features_V_24_fu_204;
reg   [7:0] features_V_25_fu_208;
reg   [7:0] features_V_26_fu_212;
reg   [7:0] features_V_27_fu_216;
reg   [7:0] features_V_28_fu_220;
reg   [7:0] features_V_29_fu_224;
reg   [7:0] features_V_30_fu_228;
reg   [7:0] features_V_31_fu_232;
reg   [7:0] ap_return_0_preg;
reg   [7:0] ap_return_1_preg;
reg   [7:0] ap_return_2_preg;
reg   [7:0] ap_return_3_preg;
reg   [7:0] ap_return_4_preg;
reg   [7:0] ap_return_5_preg;
reg   [7:0] ap_return_6_preg;
reg   [7:0] ap_return_7_preg;
reg   [7:0] ap_return_8_preg;
reg   [7:0] ap_return_9_preg;
reg   [7:0] ap_return_10_preg;
reg   [7:0] ap_return_11_preg;
reg   [7:0] ap_return_12_preg;
reg   [7:0] ap_return_13_preg;
reg   [7:0] ap_return_14_preg;
reg   [7:0] ap_return_15_preg;
reg   [7:0] ap_return_16_preg;
reg   [7:0] ap_return_17_preg;
reg   [7:0] ap_return_18_preg;
reg   [7:0] ap_return_19_preg;
reg   [7:0] ap_return_20_preg;
reg   [7:0] ap_return_21_preg;
reg   [7:0] ap_return_22_preg;
reg   [7:0] ap_return_23_preg;
reg   [7:0] ap_return_24_preg;
reg   [7:0] ap_return_25_preg;
reg   [7:0] ap_return_26_preg;
reg   [7:0] ap_return_27_preg;
reg   [7:0] ap_return_28_preg;
reg   [7:0] ap_return_29_preg;
reg   [7:0] ap_return_30_preg;
reg   [7:0] ap_return_31_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
reg    ap_condition_2632;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 ap_return_0_preg = 8'd0;
#0 ap_return_1_preg = 8'd0;
#0 ap_return_2_preg = 8'd0;
#0 ap_return_3_preg = 8'd0;
#0 ap_return_4_preg = 8'd0;
#0 ap_return_5_preg = 8'd0;
#0 ap_return_6_preg = 8'd0;
#0 ap_return_7_preg = 8'd0;
#0 ap_return_8_preg = 8'd0;
#0 ap_return_9_preg = 8'd0;
#0 ap_return_10_preg = 8'd0;
#0 ap_return_11_preg = 8'd0;
#0 ap_return_12_preg = 8'd0;
#0 ap_return_13_preg = 8'd0;
#0 ap_return_14_preg = 8'd0;
#0 ap_return_15_preg = 8'd0;
#0 ap_return_16_preg = 8'd0;
#0 ap_return_17_preg = 8'd0;
#0 ap_return_18_preg = 8'd0;
#0 ap_return_19_preg = 8'd0;
#0 ap_return_20_preg = 8'd0;
#0 ap_return_21_preg = 8'd0;
#0 ap_return_22_preg = 8'd0;
#0 ap_return_23_preg = 8'd0;
#0 ap_return_24_preg = 8'd0;
#0 ap_return_25_preg = 8'd0;
#0 ap_return_26_preg = 8'd0;
#0 ap_return_27_preg = 8'd0;
#0 ap_return_28_preg = 8'd0;
#0 ap_return_29_preg = 8'd0;
#0 ap_return_30_preg = 8'd0;
#0 ap_return_31_preg = 8'd0;
end

logistic_regression_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

logistic_regression_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

logistic_regression_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

logistic_regression_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

logistic_regression_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= features_V_31_fu_232;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= features_V_21_fu_192;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= features_V_20_fu_188;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= features_V_19_fu_184;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= features_V_18_fu_180;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= features_V_17_fu_176;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= features_V_16_fu_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_16_preg <= features_V_15_fu_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_17_preg <= features_V_14_fu_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_18_preg <= features_V_13_fu_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_19_preg <= features_V_12_fu_156;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= features_V_30_fu_228;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_20_preg <= features_V_11_fu_152;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_21_preg <= features_V_10_fu_148;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_22_preg <= features_V_9_fu_144;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_23_preg <= features_V_8_fu_140;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_24_preg <= features_V_7_fu_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_25_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_25_preg <= features_V_6_fu_132;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_26_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_26_preg <= features_V_5_fu_128;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_27_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_27_preg <= features_V_4_fu_124;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_28_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_28_preg <= features_V_3_fu_120;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_29_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_29_preg <= features_V_2_fu_116;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= features_V_29_fu_224;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_30_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_30_preg <= features_V_1_fu_112;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_31_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_31_preg <= features_V_fu_108;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= features_V_28_fu_220;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= features_V_27_fu_216;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= features_V_26_fu_212;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= features_V_25_fu_208;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= features_V_24_fu_204;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= features_V_23_fu_200;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 8'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= features_V_22_fu_196;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2632)) begin
        if ((icmp_ln27_fu_256_p2 == 1'd0)) begin
            i_fu_104 <= add_ln27_fu_262_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_104 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd10) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_10_fu_148 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd11) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_11_fu_152 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd12) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_12_fu_156 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd13) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_13_fu_160 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd14) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_14_fu_164 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd15) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_15_fu_168 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd16) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_16_fu_172 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd17) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_17_fu_176 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd18) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_18_fu_180 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd19) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_19_fu_184 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd1) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_1_fu_112 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd20) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_20_fu_188 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd21) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_21_fu_192 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd22) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_22_fu_196 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd23) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_23_fu_200 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd24) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_24_fu_204 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd25) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_25_fu_208 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd26) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_26_fu_212 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd27) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_27_fu_216 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd28) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_28_fu_220 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd29) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_29_fu_224 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd2) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_2_fu_116 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd30) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_30_fu_228 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd31) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_31_fu_232 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd3) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_3_fu_120 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd4) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_4_fu_124 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd5) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_5_fu_128 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd6) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_6_fu_132 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd7) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_7_fu_136 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd8) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_8_fu_140 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd9) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_9_fu_144 <= features_V_32_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (trunc_ln30_fu_276_p1 == 5'd0) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        features_V_fu_108 <= features_V_32_fu_272_p1;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = features_V_31_fu_232;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = features_V_30_fu_228;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = features_V_21_fu_192;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = features_V_20_fu_188;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = features_V_19_fu_184;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = features_V_18_fu_180;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = features_V_17_fu_176;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = features_V_16_fu_172;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_16 = features_V_15_fu_168;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_17 = features_V_14_fu_164;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_18 = features_V_13_fu_160;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_19 = features_V_12_fu_156;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = features_V_29_fu_224;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_20 = features_V_11_fu_152;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_21 = features_V_10_fu_148;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_22 = features_V_9_fu_144;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_23 = features_V_8_fu_140;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_24 = features_V_7_fu_136;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_25 = features_V_6_fu_132;
    end else begin
        ap_return_25 = ap_return_25_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_26 = features_V_5_fu_128;
    end else begin
        ap_return_26 = ap_return_26_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_27 = features_V_4_fu_124;
    end else begin
        ap_return_27 = ap_return_27_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_28 = features_V_3_fu_120;
    end else begin
        ap_return_28 = ap_return_28_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_29 = features_V_2_fu_116;
    end else begin
        ap_return_29 = ap_return_29_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = features_V_28_fu_220;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_30 = features_V_1_fu_112;
    end else begin
        ap_return_30 = ap_return_30_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_31 = features_V_fu_108;
    end else begin
        ap_return_31 = ap_return_31_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = features_V_27_fu_216;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = features_V_26_fu_212;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = features_V_25_fu_208;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = features_V_24_fu_204;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = features_V_23_fu_200;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = features_V_22_fu_196;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_104;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (icmp_ln27_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_fu_262_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_2632 = (~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0) | ((in_stream_TVALID_int_regslice == 1'b0) & (icmp_ln27_fu_256_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign features_V_32_fu_272_p1 = in_stream_TDATA_int_regslice[7:0];

assign icmp_ln27_fu_256_p2 = ((ap_sig_allocacmp_i_1 == 6'd32) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign trunc_ln30_fu_276_p1 = ap_sig_allocacmp_i_1[4:0];

endmodule //logistic_regression_Loop_read_input_features_proc2
