// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="logistic_regression_logistic_regression,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5eg-sfvc784-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.171545,HLS_SYN_LAT=12,HLS_SYN_TPT=13,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=769,HLS_SYN_LUT=3152,HLS_VERSION=2022_1}" *)

module logistic_regression (
        in_stream_TDATA,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        ap_clk,
        ap_rst_n,
        in_stream_TVALID,
        in_stream_TREADY,
        out_stream_TVALID,
        out_stream_TREADY
);


input  [15:0] in_stream_TDATA;
input  [1:0] in_stream_TKEEP;
input  [1:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [15:0] out_stream_TDATA;
output  [1:0] out_stream_TKEEP;
output  [1:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   ap_clk;
input   ap_rst_n;
input   in_stream_TVALID;
output   in_stream_TREADY;
output   out_stream_TVALID;
input   out_stream_TREADY;

 reg    ap_rst_n_inv;
wire    Block_entry35_proc2_U0_ap_start;
wire    Block_entry35_proc2_U0_ap_done;
wire    Block_entry35_proc2_U0_ap_continue;
wire    Block_entry35_proc2_U0_ap_idle;
wire    Block_entry35_proc2_U0_ap_ready;
wire    Block_entry35_proc2_U0_in_stream_TREADY;
wire   [31:0] Block_entry35_proc2_U0_ap_return;
wire    decision_V_9_loc_channel_full_n;
wire    sigmoid_U0_ap_start;
wire    sigmoid_U0_ap_done;
wire    sigmoid_U0_ap_continue;
wire    sigmoid_U0_ap_idle;
wire    sigmoid_U0_ap_ready;
wire   [25:0] sigmoid_U0_ap_return;
wire    op_V_channel_full_n;
wire    Block_entry3537_proc3_U0_ap_start;
wire    Block_entry3537_proc3_U0_ap_done;
wire    Block_entry3537_proc3_U0_ap_continue;
wire    Block_entry3537_proc3_U0_ap_idle;
wire    Block_entry3537_proc3_U0_ap_ready;
wire   [15:0] Block_entry3537_proc3_U0_out_stream_TDATA;
wire    Block_entry3537_proc3_U0_out_stream_TVALID;
wire   [1:0] Block_entry3537_proc3_U0_out_stream_TKEEP;
wire   [1:0] Block_entry3537_proc3_U0_out_stream_TSTRB;
wire   [0:0] Block_entry3537_proc3_U0_out_stream_TLAST;
wire   [31:0] decision_V_9_loc_channel_dout;
wire   [1:0] decision_V_9_loc_channel_num_data_valid;
wire   [1:0] decision_V_9_loc_channel_fifo_cap;
wire    decision_V_9_loc_channel_empty_n;
wire   [25:0] op_V_channel_dout;
wire   [1:0] op_V_channel_num_data_valid;
wire   [1:0] op_V_channel_fifo_cap;
wire    op_V_channel_empty_n;

logistic_regression_Block_entry35_proc2 Block_entry35_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry35_proc2_U0_ap_start),
    .ap_done(Block_entry35_proc2_U0_ap_done),
    .ap_continue(Block_entry35_proc2_U0_ap_continue),
    .ap_idle(Block_entry35_proc2_U0_ap_idle),
    .ap_ready(Block_entry35_proc2_U0_ap_ready),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TVALID(in_stream_TVALID),
    .in_stream_TREADY(Block_entry35_proc2_U0_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TLAST(in_stream_TLAST),
    .ap_return(Block_entry35_proc2_U0_ap_return)
);

logistic_regression_sigmoid sigmoid_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(sigmoid_U0_ap_start),
    .ap_done(sigmoid_U0_ap_done),
    .ap_continue(sigmoid_U0_ap_continue),
    .ap_idle(sigmoid_U0_ap_idle),
    .ap_ready(sigmoid_U0_ap_ready),
    .p_read1(decision_V_9_loc_channel_dout),
    .ap_return(sigmoid_U0_ap_return)
);

logistic_regression_Block_entry3537_proc3 Block_entry3537_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry3537_proc3_U0_ap_start),
    .ap_done(Block_entry3537_proc3_U0_ap_done),
    .ap_continue(Block_entry3537_proc3_U0_ap_continue),
    .ap_idle(Block_entry3537_proc3_U0_ap_idle),
    .ap_ready(Block_entry3537_proc3_U0_ap_ready),
    .p_read(op_V_channel_dout),
    .out_stream_TDATA(Block_entry3537_proc3_U0_out_stream_TDATA),
    .out_stream_TVALID(Block_entry3537_proc3_U0_out_stream_TVALID),
    .out_stream_TREADY(out_stream_TREADY),
    .out_stream_TKEEP(Block_entry3537_proc3_U0_out_stream_TKEEP),
    .out_stream_TSTRB(Block_entry3537_proc3_U0_out_stream_TSTRB),
    .out_stream_TLAST(Block_entry3537_proc3_U0_out_stream_TLAST)
);

logistic_regression_fifo_w32_d2_S decision_V_9_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry35_proc2_U0_ap_return),
    .if_full_n(decision_V_9_loc_channel_full_n),
    .if_write(Block_entry35_proc2_U0_ap_done),
    .if_dout(decision_V_9_loc_channel_dout),
    .if_num_data_valid(decision_V_9_loc_channel_num_data_valid),
    .if_fifo_cap(decision_V_9_loc_channel_fifo_cap),
    .if_empty_n(decision_V_9_loc_channel_empty_n),
    .if_read(sigmoid_U0_ap_ready)
);

logistic_regression_fifo_w26_d2_S op_V_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sigmoid_U0_ap_return),
    .if_full_n(op_V_channel_full_n),
    .if_write(sigmoid_U0_ap_done),
    .if_dout(op_V_channel_dout),
    .if_num_data_valid(op_V_channel_num_data_valid),
    .if_fifo_cap(op_V_channel_fifo_cap),
    .if_empty_n(op_V_channel_empty_n),
    .if_read(Block_entry3537_proc3_U0_ap_ready)
);

assign Block_entry3537_proc3_U0_ap_continue = 1'b1;

assign Block_entry3537_proc3_U0_ap_start = op_V_channel_empty_n;

assign Block_entry35_proc2_U0_ap_continue = decision_V_9_loc_channel_full_n;

assign Block_entry35_proc2_U0_ap_start = 1'b1;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign in_stream_TREADY = Block_entry35_proc2_U0_in_stream_TREADY;

assign out_stream_TDATA = Block_entry3537_proc3_U0_out_stream_TDATA;

assign out_stream_TKEEP = Block_entry3537_proc3_U0_out_stream_TKEEP;

assign out_stream_TLAST = Block_entry3537_proc3_U0_out_stream_TLAST;

assign out_stream_TSTRB = Block_entry3537_proc3_U0_out_stream_TSTRB;

assign out_stream_TVALID = Block_entry3537_proc3_U0_out_stream_TVALID;

assign sigmoid_U0_ap_continue = op_V_channel_full_n;

assign sigmoid_U0_ap_start = decision_V_9_loc_channel_empty_n;


reg find_kernel_block = 0;
// synthesis translate_off
`include "logistic_regression_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //logistic_regression

