// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="logistic_regression_logistic_regression,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.972000,HLS_SYN_LAT=92,HLS_SYN_TPT=58,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4897,HLS_SYN_LUT=5737,HLS_VERSION=2022_1}" *)

module logistic_regression (
        in_stream_TDATA,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        weights_Addr_A,
        weights_EN_A,
        weights_Din_A,
        weights_Dout_A,
        weights_WEN_A,
        weights_Clk_A,
        ap_clk,
        weights_Rst_A,
        ap_rst_n,
        weights_Addr_B,
        weights_EN_B,
        weights_Din_B,
        weights_Dout_B,
        weights_WEN_B,
        weights_Clk_B,
        weights_Rst_B,
        in_stream_TVALID,
        in_stream_TREADY,
        ap_start,
        out_stream_TVALID,
        out_stream_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] in_stream_TDATA;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
output  [31:0] weights_Addr_A;
output   weights_EN_A;
output  [15:0] weights_Din_A;
input  [15:0] weights_Dout_A;
output  [1:0] weights_WEN_A;
output   weights_Clk_A;
input   ap_clk;
output   weights_Rst_A;
input   ap_rst_n;
output  [31:0] weights_Addr_B;
output   weights_EN_B;
output  [15:0] weights_Din_B;
input  [15:0] weights_Dout_B;
output  [1:0] weights_WEN_B;
output   weights_Clk_B;
output   weights_Rst_B;
input   in_stream_TVALID;
output   in_stream_TREADY;
input   ap_start;
output   out_stream_TVALID;
input   out_stream_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Loop_read_input_features_proc2_U0_ap_start;
wire    Loop_read_input_features_proc2_U0_ap_done;
wire    Loop_read_input_features_proc2_U0_ap_continue;
wire    Loop_read_input_features_proc2_U0_ap_idle;
wire    Loop_read_input_features_proc2_U0_ap_ready;
wire    Loop_read_input_features_proc2_U0_in_stream_TREADY;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_0;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_1;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_2;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_3;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_4;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_5;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_6;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_7;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_8;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_9;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_10;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_11;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_12;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_13;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_14;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_15;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_16;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_17;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_18;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_19;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_20;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_21;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_22;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_23;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_24;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_25;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_26;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_27;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_28;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_29;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_30;
wire   [7:0] Loop_read_input_features_proc2_U0_ap_return_31;
wire    ap_channel_done_features_V_loc_channel;
wire    features_V_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_loc_channel;
wire    ap_sync_channel_write_features_V_loc_channel;
wire    ap_channel_done_features_V_1_loc_channel;
wire    features_V_1_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_1_loc_channel;
wire    ap_sync_channel_write_features_V_1_loc_channel;
wire    ap_channel_done_features_V_2_loc_channel;
wire    features_V_2_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_2_loc_channel;
wire    ap_sync_channel_write_features_V_2_loc_channel;
wire    ap_channel_done_features_V_3_loc_channel;
wire    features_V_3_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_3_loc_channel;
wire    ap_sync_channel_write_features_V_3_loc_channel;
wire    ap_channel_done_features_V_4_loc_channel;
wire    features_V_4_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_4_loc_channel;
wire    ap_sync_channel_write_features_V_4_loc_channel;
wire    ap_channel_done_features_V_5_loc_channel;
wire    features_V_5_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_5_loc_channel;
wire    ap_sync_channel_write_features_V_5_loc_channel;
wire    ap_channel_done_features_V_6_loc_channel;
wire    features_V_6_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_6_loc_channel;
wire    ap_sync_channel_write_features_V_6_loc_channel;
wire    ap_channel_done_features_V_7_loc_channel;
wire    features_V_7_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_7_loc_channel;
wire    ap_sync_channel_write_features_V_7_loc_channel;
wire    ap_channel_done_features_V_8_loc_channel;
wire    features_V_8_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_8_loc_channel;
wire    ap_sync_channel_write_features_V_8_loc_channel;
wire    ap_channel_done_features_V_9_loc_channel;
wire    features_V_9_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_9_loc_channel;
wire    ap_sync_channel_write_features_V_9_loc_channel;
wire    ap_channel_done_features_V_10_loc_channel;
wire    features_V_10_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_10_loc_channel;
wire    ap_sync_channel_write_features_V_10_loc_channel;
wire    ap_channel_done_features_V_11_loc_channel;
wire    features_V_11_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_11_loc_channel;
wire    ap_sync_channel_write_features_V_11_loc_channel;
wire    ap_channel_done_features_V_12_loc_channel;
wire    features_V_12_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_12_loc_channel;
wire    ap_sync_channel_write_features_V_12_loc_channel;
wire    ap_channel_done_features_V_13_loc_channel;
wire    features_V_13_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_13_loc_channel;
wire    ap_sync_channel_write_features_V_13_loc_channel;
wire    ap_channel_done_features_V_14_loc_channel;
wire    features_V_14_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_14_loc_channel;
wire    ap_sync_channel_write_features_V_14_loc_channel;
wire    ap_channel_done_features_V_15_loc_channel;
wire    features_V_15_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_15_loc_channel;
wire    ap_sync_channel_write_features_V_15_loc_channel;
wire    ap_channel_done_features_V_16_loc_channel;
wire    features_V_16_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_16_loc_channel;
wire    ap_sync_channel_write_features_V_16_loc_channel;
wire    ap_channel_done_features_V_17_loc_channel;
wire    features_V_17_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_17_loc_channel;
wire    ap_sync_channel_write_features_V_17_loc_channel;
wire    ap_channel_done_features_V_18_loc_channel;
wire    features_V_18_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_18_loc_channel;
wire    ap_sync_channel_write_features_V_18_loc_channel;
wire    ap_channel_done_features_V_19_loc_channel;
wire    features_V_19_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_19_loc_channel;
wire    ap_sync_channel_write_features_V_19_loc_channel;
wire    ap_channel_done_features_V_20_loc_channel;
wire    features_V_20_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_20_loc_channel;
wire    ap_sync_channel_write_features_V_20_loc_channel;
wire    ap_channel_done_features_V_21_loc_channel;
wire    features_V_21_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_21_loc_channel;
wire    ap_sync_channel_write_features_V_21_loc_channel;
wire    ap_channel_done_features_V_22_loc_channel;
wire    features_V_22_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_22_loc_channel;
wire    ap_sync_channel_write_features_V_22_loc_channel;
wire    ap_channel_done_features_V_23_loc_channel;
wire    features_V_23_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_23_loc_channel;
wire    ap_sync_channel_write_features_V_23_loc_channel;
wire    ap_channel_done_features_V_24_loc_channel;
wire    features_V_24_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_24_loc_channel;
wire    ap_sync_channel_write_features_V_24_loc_channel;
wire    ap_channel_done_features_V_25_loc_channel;
wire    features_V_25_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_25_loc_channel;
wire    ap_sync_channel_write_features_V_25_loc_channel;
wire    ap_channel_done_features_V_26_loc_channel;
wire    features_V_26_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_26_loc_channel;
wire    ap_sync_channel_write_features_V_26_loc_channel;
wire    ap_channel_done_features_V_27_loc_channel;
wire    features_V_27_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_27_loc_channel;
wire    ap_sync_channel_write_features_V_27_loc_channel;
wire    ap_channel_done_features_V_28_loc_channel;
wire    features_V_28_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_28_loc_channel;
wire    ap_sync_channel_write_features_V_28_loc_channel;
wire    ap_channel_done_features_V_29_loc_channel;
wire    features_V_29_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_29_loc_channel;
wire    ap_sync_channel_write_features_V_29_loc_channel;
wire    ap_channel_done_features_V_30_loc_channel;
wire    features_V_30_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_30_loc_channel;
wire    ap_sync_channel_write_features_V_30_loc_channel;
wire    ap_channel_done_features_V_31_loc_channel;
wire    features_V_31_loc_channel_full_n;
reg    ap_sync_reg_channel_write_features_V_31_loc_channel;
wire    ap_sync_channel_write_features_V_31_loc_channel;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_ap_start;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_ap_done;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_ap_continue;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_ap_idle;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready;
wire   [31:0] Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Addr_A;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_weights_EN_A;
wire   [1:0] Block_logistic_regression_for_cond_i_exit_proc_U0_weights_WEN_A;
wire   [15:0] Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Din_A;
wire   [31:0] Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Addr_B;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_weights_EN_B;
wire   [1:0] Block_logistic_regression_for_cond_i_exit_proc_U0_weights_WEN_B;
wire   [15:0] Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Din_B;
wire   [31:0] Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TDATA;
wire    Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TVALID;
wire   [3:0] Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TKEEP;
wire   [3:0] Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TSTRB;
wire   [0:0] Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TLAST;
wire   [7:0] features_V_31_loc_channel_dout;
wire   [1:0] features_V_31_loc_channel_num_data_valid;
wire   [1:0] features_V_31_loc_channel_fifo_cap;
wire    features_V_31_loc_channel_empty_n;
wire   [7:0] features_V_30_loc_channel_dout;
wire   [1:0] features_V_30_loc_channel_num_data_valid;
wire   [1:0] features_V_30_loc_channel_fifo_cap;
wire    features_V_30_loc_channel_empty_n;
wire   [7:0] features_V_29_loc_channel_dout;
wire   [1:0] features_V_29_loc_channel_num_data_valid;
wire   [1:0] features_V_29_loc_channel_fifo_cap;
wire    features_V_29_loc_channel_empty_n;
wire   [7:0] features_V_28_loc_channel_dout;
wire   [1:0] features_V_28_loc_channel_num_data_valid;
wire   [1:0] features_V_28_loc_channel_fifo_cap;
wire    features_V_28_loc_channel_empty_n;
wire   [7:0] features_V_27_loc_channel_dout;
wire   [1:0] features_V_27_loc_channel_num_data_valid;
wire   [1:0] features_V_27_loc_channel_fifo_cap;
wire    features_V_27_loc_channel_empty_n;
wire   [7:0] features_V_26_loc_channel_dout;
wire   [1:0] features_V_26_loc_channel_num_data_valid;
wire   [1:0] features_V_26_loc_channel_fifo_cap;
wire    features_V_26_loc_channel_empty_n;
wire   [7:0] features_V_25_loc_channel_dout;
wire   [1:0] features_V_25_loc_channel_num_data_valid;
wire   [1:0] features_V_25_loc_channel_fifo_cap;
wire    features_V_25_loc_channel_empty_n;
wire   [7:0] features_V_24_loc_channel_dout;
wire   [1:0] features_V_24_loc_channel_num_data_valid;
wire   [1:0] features_V_24_loc_channel_fifo_cap;
wire    features_V_24_loc_channel_empty_n;
wire   [7:0] features_V_23_loc_channel_dout;
wire   [1:0] features_V_23_loc_channel_num_data_valid;
wire   [1:0] features_V_23_loc_channel_fifo_cap;
wire    features_V_23_loc_channel_empty_n;
wire   [7:0] features_V_22_loc_channel_dout;
wire   [1:0] features_V_22_loc_channel_num_data_valid;
wire   [1:0] features_V_22_loc_channel_fifo_cap;
wire    features_V_22_loc_channel_empty_n;
wire   [7:0] features_V_21_loc_channel_dout;
wire   [1:0] features_V_21_loc_channel_num_data_valid;
wire   [1:0] features_V_21_loc_channel_fifo_cap;
wire    features_V_21_loc_channel_empty_n;
wire   [7:0] features_V_20_loc_channel_dout;
wire   [1:0] features_V_20_loc_channel_num_data_valid;
wire   [1:0] features_V_20_loc_channel_fifo_cap;
wire    features_V_20_loc_channel_empty_n;
wire   [7:0] features_V_19_loc_channel_dout;
wire   [1:0] features_V_19_loc_channel_num_data_valid;
wire   [1:0] features_V_19_loc_channel_fifo_cap;
wire    features_V_19_loc_channel_empty_n;
wire   [7:0] features_V_18_loc_channel_dout;
wire   [1:0] features_V_18_loc_channel_num_data_valid;
wire   [1:0] features_V_18_loc_channel_fifo_cap;
wire    features_V_18_loc_channel_empty_n;
wire   [7:0] features_V_17_loc_channel_dout;
wire   [1:0] features_V_17_loc_channel_num_data_valid;
wire   [1:0] features_V_17_loc_channel_fifo_cap;
wire    features_V_17_loc_channel_empty_n;
wire   [7:0] features_V_16_loc_channel_dout;
wire   [1:0] features_V_16_loc_channel_num_data_valid;
wire   [1:0] features_V_16_loc_channel_fifo_cap;
wire    features_V_16_loc_channel_empty_n;
wire   [7:0] features_V_15_loc_channel_dout;
wire   [1:0] features_V_15_loc_channel_num_data_valid;
wire   [1:0] features_V_15_loc_channel_fifo_cap;
wire    features_V_15_loc_channel_empty_n;
wire   [7:0] features_V_14_loc_channel_dout;
wire   [1:0] features_V_14_loc_channel_num_data_valid;
wire   [1:0] features_V_14_loc_channel_fifo_cap;
wire    features_V_14_loc_channel_empty_n;
wire   [7:0] features_V_13_loc_channel_dout;
wire   [1:0] features_V_13_loc_channel_num_data_valid;
wire   [1:0] features_V_13_loc_channel_fifo_cap;
wire    features_V_13_loc_channel_empty_n;
wire   [7:0] features_V_12_loc_channel_dout;
wire   [1:0] features_V_12_loc_channel_num_data_valid;
wire   [1:0] features_V_12_loc_channel_fifo_cap;
wire    features_V_12_loc_channel_empty_n;
wire   [7:0] features_V_11_loc_channel_dout;
wire   [1:0] features_V_11_loc_channel_num_data_valid;
wire   [1:0] features_V_11_loc_channel_fifo_cap;
wire    features_V_11_loc_channel_empty_n;
wire   [7:0] features_V_10_loc_channel_dout;
wire   [1:0] features_V_10_loc_channel_num_data_valid;
wire   [1:0] features_V_10_loc_channel_fifo_cap;
wire    features_V_10_loc_channel_empty_n;
wire   [7:0] features_V_9_loc_channel_dout;
wire   [1:0] features_V_9_loc_channel_num_data_valid;
wire   [1:0] features_V_9_loc_channel_fifo_cap;
wire    features_V_9_loc_channel_empty_n;
wire   [7:0] features_V_8_loc_channel_dout;
wire   [1:0] features_V_8_loc_channel_num_data_valid;
wire   [1:0] features_V_8_loc_channel_fifo_cap;
wire    features_V_8_loc_channel_empty_n;
wire   [7:0] features_V_7_loc_channel_dout;
wire   [1:0] features_V_7_loc_channel_num_data_valid;
wire   [1:0] features_V_7_loc_channel_fifo_cap;
wire    features_V_7_loc_channel_empty_n;
wire   [7:0] features_V_6_loc_channel_dout;
wire   [1:0] features_V_6_loc_channel_num_data_valid;
wire   [1:0] features_V_6_loc_channel_fifo_cap;
wire    features_V_6_loc_channel_empty_n;
wire   [7:0] features_V_5_loc_channel_dout;
wire   [1:0] features_V_5_loc_channel_num_data_valid;
wire   [1:0] features_V_5_loc_channel_fifo_cap;
wire    features_V_5_loc_channel_empty_n;
wire   [7:0] features_V_4_loc_channel_dout;
wire   [1:0] features_V_4_loc_channel_num_data_valid;
wire   [1:0] features_V_4_loc_channel_fifo_cap;
wire    features_V_4_loc_channel_empty_n;
wire   [7:0] features_V_3_loc_channel_dout;
wire   [1:0] features_V_3_loc_channel_num_data_valid;
wire   [1:0] features_V_3_loc_channel_fifo_cap;
wire    features_V_3_loc_channel_empty_n;
wire   [7:0] features_V_2_loc_channel_dout;
wire   [1:0] features_V_2_loc_channel_num_data_valid;
wire   [1:0] features_V_2_loc_channel_fifo_cap;
wire    features_V_2_loc_channel_empty_n;
wire   [7:0] features_V_1_loc_channel_dout;
wire   [1:0] features_V_1_loc_channel_num_data_valid;
wire   [1:0] features_V_1_loc_channel_fifo_cap;
wire    features_V_1_loc_channel_empty_n;
wire   [7:0] features_V_loc_channel_dout;
wire   [1:0] features_V_loc_channel_num_data_valid;
wire   [1:0] features_V_loc_channel_fifo_cap;
wire    features_V_loc_channel_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready;
wire    ap_sync_Loop_read_input_features_proc2_U0_ap_ready;
reg    ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready;
wire    ap_sync_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_features_V_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_1_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_2_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_3_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_4_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_5_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_6_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_7_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_8_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_9_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_10_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_11_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_12_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_13_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_14_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_15_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_16_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_17_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_18_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_19_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_20_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_21_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_22_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_23_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_24_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_25_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_26_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_27_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_28_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_29_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_30_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_features_V_31_loc_channel = 1'b0;
#0 ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready = 1'b0;
end

logistic_regression_Loop_read_input_features_proc2 Loop_read_input_features_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_read_input_features_proc2_U0_ap_start),
    .ap_done(Loop_read_input_features_proc2_U0_ap_done),
    .ap_continue(Loop_read_input_features_proc2_U0_ap_continue),
    .ap_idle(Loop_read_input_features_proc2_U0_ap_idle),
    .ap_ready(Loop_read_input_features_proc2_U0_ap_ready),
    .in_stream_TVALID(in_stream_TVALID),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TREADY(Loop_read_input_features_proc2_U0_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TLAST(in_stream_TLAST),
    .ap_return_0(Loop_read_input_features_proc2_U0_ap_return_0),
    .ap_return_1(Loop_read_input_features_proc2_U0_ap_return_1),
    .ap_return_2(Loop_read_input_features_proc2_U0_ap_return_2),
    .ap_return_3(Loop_read_input_features_proc2_U0_ap_return_3),
    .ap_return_4(Loop_read_input_features_proc2_U0_ap_return_4),
    .ap_return_5(Loop_read_input_features_proc2_U0_ap_return_5),
    .ap_return_6(Loop_read_input_features_proc2_U0_ap_return_6),
    .ap_return_7(Loop_read_input_features_proc2_U0_ap_return_7),
    .ap_return_8(Loop_read_input_features_proc2_U0_ap_return_8),
    .ap_return_9(Loop_read_input_features_proc2_U0_ap_return_9),
    .ap_return_10(Loop_read_input_features_proc2_U0_ap_return_10),
    .ap_return_11(Loop_read_input_features_proc2_U0_ap_return_11),
    .ap_return_12(Loop_read_input_features_proc2_U0_ap_return_12),
    .ap_return_13(Loop_read_input_features_proc2_U0_ap_return_13),
    .ap_return_14(Loop_read_input_features_proc2_U0_ap_return_14),
    .ap_return_15(Loop_read_input_features_proc2_U0_ap_return_15),
    .ap_return_16(Loop_read_input_features_proc2_U0_ap_return_16),
    .ap_return_17(Loop_read_input_features_proc2_U0_ap_return_17),
    .ap_return_18(Loop_read_input_features_proc2_U0_ap_return_18),
    .ap_return_19(Loop_read_input_features_proc2_U0_ap_return_19),
    .ap_return_20(Loop_read_input_features_proc2_U0_ap_return_20),
    .ap_return_21(Loop_read_input_features_proc2_U0_ap_return_21),
    .ap_return_22(Loop_read_input_features_proc2_U0_ap_return_22),
    .ap_return_23(Loop_read_input_features_proc2_U0_ap_return_23),
    .ap_return_24(Loop_read_input_features_proc2_U0_ap_return_24),
    .ap_return_25(Loop_read_input_features_proc2_U0_ap_return_25),
    .ap_return_26(Loop_read_input_features_proc2_U0_ap_return_26),
    .ap_return_27(Loop_read_input_features_proc2_U0_ap_return_27),
    .ap_return_28(Loop_read_input_features_proc2_U0_ap_return_28),
    .ap_return_29(Loop_read_input_features_proc2_U0_ap_return_29),
    .ap_return_30(Loop_read_input_features_proc2_U0_ap_return_30),
    .ap_return_31(Loop_read_input_features_proc2_U0_ap_return_31)
);

logistic_regression_Block_logistic_regression_for_cond_i_exit_proc Block_logistic_regression_for_cond_i_exit_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_start),
    .ap_done(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_done),
    .ap_continue(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_continue),
    .ap_idle(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_idle),
    .ap_ready(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready),
    .weights_Addr_A(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Addr_A),
    .weights_EN_A(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_EN_A),
    .weights_WEN_A(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_WEN_A),
    .weights_Din_A(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Din_A),
    .weights_Dout_A(weights_Dout_A),
    .weights_Addr_B(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Addr_B),
    .weights_EN_B(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_EN_B),
    .weights_WEN_B(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_WEN_B),
    .weights_Din_B(Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Din_B),
    .weights_Dout_B(weights_Dout_B),
    .p_read(features_V_loc_channel_dout),
    .p_read1(features_V_1_loc_channel_dout),
    .p_read2(features_V_2_loc_channel_dout),
    .p_read3(features_V_3_loc_channel_dout),
    .p_read4(features_V_4_loc_channel_dout),
    .p_read5(features_V_5_loc_channel_dout),
    .p_read6(features_V_6_loc_channel_dout),
    .p_read7(features_V_7_loc_channel_dout),
    .p_read8(features_V_8_loc_channel_dout),
    .p_read9(features_V_9_loc_channel_dout),
    .p_read10(features_V_10_loc_channel_dout),
    .p_read11(features_V_11_loc_channel_dout),
    .p_read12(features_V_12_loc_channel_dout),
    .p_read13(features_V_13_loc_channel_dout),
    .p_read14(features_V_14_loc_channel_dout),
    .p_read15(features_V_15_loc_channel_dout),
    .p_read16(features_V_16_loc_channel_dout),
    .p_read17(features_V_17_loc_channel_dout),
    .p_read18(features_V_18_loc_channel_dout),
    .p_read19(features_V_19_loc_channel_dout),
    .p_read20(features_V_20_loc_channel_dout),
    .p_read21(features_V_21_loc_channel_dout),
    .p_read22(features_V_22_loc_channel_dout),
    .p_read23(features_V_23_loc_channel_dout),
    .p_read24(features_V_24_loc_channel_dout),
    .p_read25(features_V_25_loc_channel_dout),
    .p_read26(features_V_26_loc_channel_dout),
    .p_read27(features_V_27_loc_channel_dout),
    .p_read28(features_V_28_loc_channel_dout),
    .p_read29(features_V_29_loc_channel_dout),
    .p_read30(features_V_30_loc_channel_dout),
    .p_read31(features_V_31_loc_channel_dout),
    .out_stream_TDATA(Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TDATA),
    .out_stream_TVALID(Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TVALID),
    .out_stream_TREADY(out_stream_TREADY),
    .out_stream_TKEEP(Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TKEEP),
    .out_stream_TSTRB(Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TSTRB),
    .out_stream_TLAST(Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TLAST)
);

logistic_regression_fifo_w8_d2_S features_V_31_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_0),
    .if_full_n(features_V_31_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_31_loc_channel),
    .if_dout(features_V_31_loc_channel_dout),
    .if_num_data_valid(features_V_31_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_31_loc_channel_fifo_cap),
    .if_empty_n(features_V_31_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_30_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_1),
    .if_full_n(features_V_30_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_30_loc_channel),
    .if_dout(features_V_30_loc_channel_dout),
    .if_num_data_valid(features_V_30_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_30_loc_channel_fifo_cap),
    .if_empty_n(features_V_30_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_29_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_2),
    .if_full_n(features_V_29_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_29_loc_channel),
    .if_dout(features_V_29_loc_channel_dout),
    .if_num_data_valid(features_V_29_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_29_loc_channel_fifo_cap),
    .if_empty_n(features_V_29_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_28_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_3),
    .if_full_n(features_V_28_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_28_loc_channel),
    .if_dout(features_V_28_loc_channel_dout),
    .if_num_data_valid(features_V_28_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_28_loc_channel_fifo_cap),
    .if_empty_n(features_V_28_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_27_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_4),
    .if_full_n(features_V_27_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_27_loc_channel),
    .if_dout(features_V_27_loc_channel_dout),
    .if_num_data_valid(features_V_27_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_27_loc_channel_fifo_cap),
    .if_empty_n(features_V_27_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_26_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_5),
    .if_full_n(features_V_26_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_26_loc_channel),
    .if_dout(features_V_26_loc_channel_dout),
    .if_num_data_valid(features_V_26_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_26_loc_channel_fifo_cap),
    .if_empty_n(features_V_26_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_25_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_6),
    .if_full_n(features_V_25_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_25_loc_channel),
    .if_dout(features_V_25_loc_channel_dout),
    .if_num_data_valid(features_V_25_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_25_loc_channel_fifo_cap),
    .if_empty_n(features_V_25_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_24_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_7),
    .if_full_n(features_V_24_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_24_loc_channel),
    .if_dout(features_V_24_loc_channel_dout),
    .if_num_data_valid(features_V_24_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_24_loc_channel_fifo_cap),
    .if_empty_n(features_V_24_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_23_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_8),
    .if_full_n(features_V_23_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_23_loc_channel),
    .if_dout(features_V_23_loc_channel_dout),
    .if_num_data_valid(features_V_23_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_23_loc_channel_fifo_cap),
    .if_empty_n(features_V_23_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_22_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_9),
    .if_full_n(features_V_22_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_22_loc_channel),
    .if_dout(features_V_22_loc_channel_dout),
    .if_num_data_valid(features_V_22_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_22_loc_channel_fifo_cap),
    .if_empty_n(features_V_22_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_21_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_10),
    .if_full_n(features_V_21_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_21_loc_channel),
    .if_dout(features_V_21_loc_channel_dout),
    .if_num_data_valid(features_V_21_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_21_loc_channel_fifo_cap),
    .if_empty_n(features_V_21_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_20_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_11),
    .if_full_n(features_V_20_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_20_loc_channel),
    .if_dout(features_V_20_loc_channel_dout),
    .if_num_data_valid(features_V_20_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_20_loc_channel_fifo_cap),
    .if_empty_n(features_V_20_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_19_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_12),
    .if_full_n(features_V_19_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_19_loc_channel),
    .if_dout(features_V_19_loc_channel_dout),
    .if_num_data_valid(features_V_19_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_19_loc_channel_fifo_cap),
    .if_empty_n(features_V_19_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_18_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_13),
    .if_full_n(features_V_18_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_18_loc_channel),
    .if_dout(features_V_18_loc_channel_dout),
    .if_num_data_valid(features_V_18_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_18_loc_channel_fifo_cap),
    .if_empty_n(features_V_18_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_17_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_14),
    .if_full_n(features_V_17_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_17_loc_channel),
    .if_dout(features_V_17_loc_channel_dout),
    .if_num_data_valid(features_V_17_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_17_loc_channel_fifo_cap),
    .if_empty_n(features_V_17_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_16_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_15),
    .if_full_n(features_V_16_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_16_loc_channel),
    .if_dout(features_V_16_loc_channel_dout),
    .if_num_data_valid(features_V_16_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_16_loc_channel_fifo_cap),
    .if_empty_n(features_V_16_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_15_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_16),
    .if_full_n(features_V_15_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_15_loc_channel),
    .if_dout(features_V_15_loc_channel_dout),
    .if_num_data_valid(features_V_15_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_15_loc_channel_fifo_cap),
    .if_empty_n(features_V_15_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_14_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_17),
    .if_full_n(features_V_14_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_14_loc_channel),
    .if_dout(features_V_14_loc_channel_dout),
    .if_num_data_valid(features_V_14_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_14_loc_channel_fifo_cap),
    .if_empty_n(features_V_14_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_13_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_18),
    .if_full_n(features_V_13_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_13_loc_channel),
    .if_dout(features_V_13_loc_channel_dout),
    .if_num_data_valid(features_V_13_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_13_loc_channel_fifo_cap),
    .if_empty_n(features_V_13_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_12_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_19),
    .if_full_n(features_V_12_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_12_loc_channel),
    .if_dout(features_V_12_loc_channel_dout),
    .if_num_data_valid(features_V_12_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_12_loc_channel_fifo_cap),
    .if_empty_n(features_V_12_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_11_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_20),
    .if_full_n(features_V_11_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_11_loc_channel),
    .if_dout(features_V_11_loc_channel_dout),
    .if_num_data_valid(features_V_11_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_11_loc_channel_fifo_cap),
    .if_empty_n(features_V_11_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_10_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_21),
    .if_full_n(features_V_10_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_10_loc_channel),
    .if_dout(features_V_10_loc_channel_dout),
    .if_num_data_valid(features_V_10_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_10_loc_channel_fifo_cap),
    .if_empty_n(features_V_10_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_9_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_22),
    .if_full_n(features_V_9_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_9_loc_channel),
    .if_dout(features_V_9_loc_channel_dout),
    .if_num_data_valid(features_V_9_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_9_loc_channel_fifo_cap),
    .if_empty_n(features_V_9_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_8_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_23),
    .if_full_n(features_V_8_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_8_loc_channel),
    .if_dout(features_V_8_loc_channel_dout),
    .if_num_data_valid(features_V_8_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_8_loc_channel_fifo_cap),
    .if_empty_n(features_V_8_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_7_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_24),
    .if_full_n(features_V_7_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_7_loc_channel),
    .if_dout(features_V_7_loc_channel_dout),
    .if_num_data_valid(features_V_7_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_7_loc_channel_fifo_cap),
    .if_empty_n(features_V_7_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_6_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_25),
    .if_full_n(features_V_6_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_6_loc_channel),
    .if_dout(features_V_6_loc_channel_dout),
    .if_num_data_valid(features_V_6_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_6_loc_channel_fifo_cap),
    .if_empty_n(features_V_6_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_5_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_26),
    .if_full_n(features_V_5_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_5_loc_channel),
    .if_dout(features_V_5_loc_channel_dout),
    .if_num_data_valid(features_V_5_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_5_loc_channel_fifo_cap),
    .if_empty_n(features_V_5_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_4_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_27),
    .if_full_n(features_V_4_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_4_loc_channel),
    .if_dout(features_V_4_loc_channel_dout),
    .if_num_data_valid(features_V_4_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_4_loc_channel_fifo_cap),
    .if_empty_n(features_V_4_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_3_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_28),
    .if_full_n(features_V_3_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_3_loc_channel),
    .if_dout(features_V_3_loc_channel_dout),
    .if_num_data_valid(features_V_3_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_3_loc_channel_fifo_cap),
    .if_empty_n(features_V_3_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_2_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_29),
    .if_full_n(features_V_2_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_2_loc_channel),
    .if_dout(features_V_2_loc_channel_dout),
    .if_num_data_valid(features_V_2_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_2_loc_channel_fifo_cap),
    .if_empty_n(features_V_2_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_1_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_30),
    .if_full_n(features_V_1_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_1_loc_channel),
    .if_dout(features_V_1_loc_channel_dout),
    .if_num_data_valid(features_V_1_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_1_loc_channel_fifo_cap),
    .if_empty_n(features_V_1_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

logistic_regression_fifo_w8_d2_S features_V_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_read_input_features_proc2_U0_ap_return_31),
    .if_full_n(features_V_loc_channel_full_n),
    .if_write(ap_channel_done_features_V_loc_channel),
    .if_dout(features_V_loc_channel_dout),
    .if_num_data_valid(features_V_loc_channel_num_data_valid),
    .if_fifo_cap(features_V_loc_channel_fifo_cap),
    .if_empty_n(features_V_loc_channel_empty_n),
    .if_read(Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready <= ap_sync_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready <= ap_sync_Loop_read_input_features_proc2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_10_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_10_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_10_loc_channel <= ap_sync_channel_write_features_V_10_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_11_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_11_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_11_loc_channel <= ap_sync_channel_write_features_V_11_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_12_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_12_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_12_loc_channel <= ap_sync_channel_write_features_V_12_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_13_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_13_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_13_loc_channel <= ap_sync_channel_write_features_V_13_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_14_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_14_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_14_loc_channel <= ap_sync_channel_write_features_V_14_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_15_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_15_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_15_loc_channel <= ap_sync_channel_write_features_V_15_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_16_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_16_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_16_loc_channel <= ap_sync_channel_write_features_V_16_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_17_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_17_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_17_loc_channel <= ap_sync_channel_write_features_V_17_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_18_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_18_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_18_loc_channel <= ap_sync_channel_write_features_V_18_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_19_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_19_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_19_loc_channel <= ap_sync_channel_write_features_V_19_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_1_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_1_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_1_loc_channel <= ap_sync_channel_write_features_V_1_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_20_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_20_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_20_loc_channel <= ap_sync_channel_write_features_V_20_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_21_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_21_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_21_loc_channel <= ap_sync_channel_write_features_V_21_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_22_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_22_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_22_loc_channel <= ap_sync_channel_write_features_V_22_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_23_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_23_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_23_loc_channel <= ap_sync_channel_write_features_V_23_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_24_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_24_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_24_loc_channel <= ap_sync_channel_write_features_V_24_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_25_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_25_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_25_loc_channel <= ap_sync_channel_write_features_V_25_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_26_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_26_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_26_loc_channel <= ap_sync_channel_write_features_V_26_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_27_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_27_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_27_loc_channel <= ap_sync_channel_write_features_V_27_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_28_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_28_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_28_loc_channel <= ap_sync_channel_write_features_V_28_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_29_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_29_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_29_loc_channel <= ap_sync_channel_write_features_V_29_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_2_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_2_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_2_loc_channel <= ap_sync_channel_write_features_V_2_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_30_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_30_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_30_loc_channel <= ap_sync_channel_write_features_V_30_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_31_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_31_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_31_loc_channel <= ap_sync_channel_write_features_V_31_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_3_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_3_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_3_loc_channel <= ap_sync_channel_write_features_V_3_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_4_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_4_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_4_loc_channel <= ap_sync_channel_write_features_V_4_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_5_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_5_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_5_loc_channel <= ap_sync_channel_write_features_V_5_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_6_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_6_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_6_loc_channel <= ap_sync_channel_write_features_V_6_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_7_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_7_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_7_loc_channel <= ap_sync_channel_write_features_V_7_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_8_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_8_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_8_loc_channel <= ap_sync_channel_write_features_V_8_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_9_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_9_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_9_loc_channel <= ap_sync_channel_write_features_V_9_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_features_V_loc_channel <= 1'b0;
    end else begin
        if (((Loop_read_input_features_proc2_U0_ap_done & Loop_read_input_features_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_features_V_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_features_V_loc_channel <= ap_sync_channel_write_features_V_loc_channel;
        end
    end
end

assign Block_logistic_regression_for_cond_i_exit_proc_U0_ap_continue = 1'b1;

assign Block_logistic_regression_for_cond_i_exit_proc_U0_ap_start = (features_V_loc_channel_empty_n & features_V_9_loc_channel_empty_n & features_V_8_loc_channel_empty_n & features_V_7_loc_channel_empty_n & features_V_6_loc_channel_empty_n & features_V_5_loc_channel_empty_n & features_V_4_loc_channel_empty_n & features_V_3_loc_channel_empty_n & features_V_31_loc_channel_empty_n & features_V_30_loc_channel_empty_n & features_V_2_loc_channel_empty_n & features_V_29_loc_channel_empty_n & features_V_28_loc_channel_empty_n & features_V_27_loc_channel_empty_n & features_V_26_loc_channel_empty_n & features_V_25_loc_channel_empty_n & features_V_24_loc_channel_empty_n & features_V_23_loc_channel_empty_n & features_V_22_loc_channel_empty_n & features_V_21_loc_channel_empty_n & features_V_20_loc_channel_empty_n & features_V_1_loc_channel_empty_n & features_V_19_loc_channel_empty_n & features_V_18_loc_channel_empty_n & features_V_17_loc_channel_empty_n & features_V_16_loc_channel_empty_n & features_V_15_loc_channel_empty_n & features_V_14_loc_channel_empty_n & features_V_13_loc_channel_empty_n & features_V_12_loc_channel_empty_n & features_V_11_loc_channel_empty_n & features_V_10_loc_channel_empty_n & (ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_read_input_features_proc2_U0_ap_continue = (ap_sync_channel_write_features_V_loc_channel & ap_sync_channel_write_features_V_9_loc_channel & ap_sync_channel_write_features_V_8_loc_channel & ap_sync_channel_write_features_V_7_loc_channel & ap_sync_channel_write_features_V_6_loc_channel & ap_sync_channel_write_features_V_5_loc_channel & ap_sync_channel_write_features_V_4_loc_channel & ap_sync_channel_write_features_V_3_loc_channel & ap_sync_channel_write_features_V_31_loc_channel & ap_sync_channel_write_features_V_30_loc_channel & ap_sync_channel_write_features_V_2_loc_channel & ap_sync_channel_write_features_V_29_loc_channel & ap_sync_channel_write_features_V_28_loc_channel & ap_sync_channel_write_features_V_27_loc_channel & ap_sync_channel_write_features_V_26_loc_channel & ap_sync_channel_write_features_V_25_loc_channel & ap_sync_channel_write_features_V_24_loc_channel & ap_sync_channel_write_features_V_23_loc_channel & ap_sync_channel_write_features_V_22_loc_channel & ap_sync_channel_write_features_V_21_loc_channel & ap_sync_channel_write_features_V_20_loc_channel & ap_sync_channel_write_features_V_1_loc_channel & ap_sync_channel_write_features_V_19_loc_channel & ap_sync_channel_write_features_V_18_loc_channel & ap_sync_channel_write_features_V_17_loc_channel & ap_sync_channel_write_features_V_16_loc_channel & ap_sync_channel_write_features_V_15_loc_channel & ap_sync_channel_write_features_V_14_loc_channel & ap_sync_channel_write_features_V_13_loc_channel & ap_sync_channel_write_features_V_12_loc_channel & ap_sync_channel_write_features_V_11_loc_channel & ap_sync_channel_write_features_V_10_loc_channel);

assign Loop_read_input_features_proc2_U0_ap_start = ((ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready ^ 1'b1) & ap_start);

assign ap_channel_done_features_V_10_loc_channel = ((ap_sync_reg_channel_write_features_V_10_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_11_loc_channel = ((ap_sync_reg_channel_write_features_V_11_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_12_loc_channel = ((ap_sync_reg_channel_write_features_V_12_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_13_loc_channel = ((ap_sync_reg_channel_write_features_V_13_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_14_loc_channel = ((ap_sync_reg_channel_write_features_V_14_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_15_loc_channel = ((ap_sync_reg_channel_write_features_V_15_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_16_loc_channel = ((ap_sync_reg_channel_write_features_V_16_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_17_loc_channel = ((ap_sync_reg_channel_write_features_V_17_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_18_loc_channel = ((ap_sync_reg_channel_write_features_V_18_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_19_loc_channel = ((ap_sync_reg_channel_write_features_V_19_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_1_loc_channel = ((ap_sync_reg_channel_write_features_V_1_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_20_loc_channel = ((ap_sync_reg_channel_write_features_V_20_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_21_loc_channel = ((ap_sync_reg_channel_write_features_V_21_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_22_loc_channel = ((ap_sync_reg_channel_write_features_V_22_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_23_loc_channel = ((ap_sync_reg_channel_write_features_V_23_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_24_loc_channel = ((ap_sync_reg_channel_write_features_V_24_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_25_loc_channel = ((ap_sync_reg_channel_write_features_V_25_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_26_loc_channel = ((ap_sync_reg_channel_write_features_V_26_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_27_loc_channel = ((ap_sync_reg_channel_write_features_V_27_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_28_loc_channel = ((ap_sync_reg_channel_write_features_V_28_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_29_loc_channel = ((ap_sync_reg_channel_write_features_V_29_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_2_loc_channel = ((ap_sync_reg_channel_write_features_V_2_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_30_loc_channel = ((ap_sync_reg_channel_write_features_V_30_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_31_loc_channel = ((ap_sync_reg_channel_write_features_V_31_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_3_loc_channel = ((ap_sync_reg_channel_write_features_V_3_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_4_loc_channel = ((ap_sync_reg_channel_write_features_V_4_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_5_loc_channel = ((ap_sync_reg_channel_write_features_V_5_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_6_loc_channel = ((ap_sync_reg_channel_write_features_V_6_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_7_loc_channel = ((ap_sync_reg_channel_write_features_V_7_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_8_loc_channel = ((ap_sync_reg_channel_write_features_V_8_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_9_loc_channel = ((ap_sync_reg_channel_write_features_V_9_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_channel_done_features_V_loc_channel = ((ap_sync_reg_channel_write_features_V_loc_channel ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_done);

assign ap_done = Block_logistic_regression_for_cond_i_exit_proc_U0_ap_done;

assign ap_idle = ((features_V_loc_channel_empty_n ^ 1'b1) & (features_V_1_loc_channel_empty_n ^ 1'b1) & (features_V_2_loc_channel_empty_n ^ 1'b1) & (features_V_3_loc_channel_empty_n ^ 1'b1) & (features_V_4_loc_channel_empty_n ^ 1'b1) & (features_V_5_loc_channel_empty_n ^ 1'b1) & (features_V_6_loc_channel_empty_n ^ 1'b1) & (features_V_7_loc_channel_empty_n ^ 1'b1) & (features_V_8_loc_channel_empty_n ^ 1'b1) & (features_V_9_loc_channel_empty_n ^ 1'b1) & (features_V_10_loc_channel_empty_n ^ 1'b1) & (features_V_11_loc_channel_empty_n ^ 1'b1) & (features_V_12_loc_channel_empty_n ^ 1'b1) & (features_V_13_loc_channel_empty_n ^ 1'b1) & (features_V_14_loc_channel_empty_n ^ 1'b1) & (features_V_15_loc_channel_empty_n ^ 1'b1) & (features_V_16_loc_channel_empty_n ^ 1'b1) & (features_V_17_loc_channel_empty_n ^ 1'b1) & (features_V_18_loc_channel_empty_n ^ 1'b1) & (features_V_19_loc_channel_empty_n ^ 1'b1) & (features_V_20_loc_channel_empty_n ^ 1'b1) & (features_V_21_loc_channel_empty_n ^ 1'b1) & (features_V_22_loc_channel_empty_n ^ 1'b1) & (features_V_23_loc_channel_empty_n ^ 1'b1) & (features_V_24_loc_channel_empty_n ^ 1'b1) & (features_V_25_loc_channel_empty_n ^ 1'b1) & (features_V_26_loc_channel_empty_n ^ 1'b1) & (features_V_27_loc_channel_empty_n ^ 1'b1) & (features_V_28_loc_channel_empty_n ^ 1'b1) & (features_V_29_loc_channel_empty_n ^ 1'b1) & (features_V_30_loc_channel_empty_n ^ 1'b1) & (features_V_31_loc_channel_empty_n ^ 1'b1) & Loop_read_input_features_proc2_U0_ap_idle & Block_logistic_regression_for_cond_i_exit_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready = (ap_sync_reg_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready | Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready);

assign ap_sync_Loop_read_input_features_proc2_U0_ap_ready = (ap_sync_reg_Loop_read_input_features_proc2_U0_ap_ready | Loop_read_input_features_proc2_U0_ap_ready);

assign ap_sync_channel_write_features_V_10_loc_channel = ((features_V_10_loc_channel_full_n & ap_channel_done_features_V_10_loc_channel) | ap_sync_reg_channel_write_features_V_10_loc_channel);

assign ap_sync_channel_write_features_V_11_loc_channel = ((features_V_11_loc_channel_full_n & ap_channel_done_features_V_11_loc_channel) | ap_sync_reg_channel_write_features_V_11_loc_channel);

assign ap_sync_channel_write_features_V_12_loc_channel = ((features_V_12_loc_channel_full_n & ap_channel_done_features_V_12_loc_channel) | ap_sync_reg_channel_write_features_V_12_loc_channel);

assign ap_sync_channel_write_features_V_13_loc_channel = ((features_V_13_loc_channel_full_n & ap_channel_done_features_V_13_loc_channel) | ap_sync_reg_channel_write_features_V_13_loc_channel);

assign ap_sync_channel_write_features_V_14_loc_channel = ((features_V_14_loc_channel_full_n & ap_channel_done_features_V_14_loc_channel) | ap_sync_reg_channel_write_features_V_14_loc_channel);

assign ap_sync_channel_write_features_V_15_loc_channel = ((features_V_15_loc_channel_full_n & ap_channel_done_features_V_15_loc_channel) | ap_sync_reg_channel_write_features_V_15_loc_channel);

assign ap_sync_channel_write_features_V_16_loc_channel = ((features_V_16_loc_channel_full_n & ap_channel_done_features_V_16_loc_channel) | ap_sync_reg_channel_write_features_V_16_loc_channel);

assign ap_sync_channel_write_features_V_17_loc_channel = ((features_V_17_loc_channel_full_n & ap_channel_done_features_V_17_loc_channel) | ap_sync_reg_channel_write_features_V_17_loc_channel);

assign ap_sync_channel_write_features_V_18_loc_channel = ((features_V_18_loc_channel_full_n & ap_channel_done_features_V_18_loc_channel) | ap_sync_reg_channel_write_features_V_18_loc_channel);

assign ap_sync_channel_write_features_V_19_loc_channel = ((features_V_19_loc_channel_full_n & ap_channel_done_features_V_19_loc_channel) | ap_sync_reg_channel_write_features_V_19_loc_channel);

assign ap_sync_channel_write_features_V_1_loc_channel = ((features_V_1_loc_channel_full_n & ap_channel_done_features_V_1_loc_channel) | ap_sync_reg_channel_write_features_V_1_loc_channel);

assign ap_sync_channel_write_features_V_20_loc_channel = ((features_V_20_loc_channel_full_n & ap_channel_done_features_V_20_loc_channel) | ap_sync_reg_channel_write_features_V_20_loc_channel);

assign ap_sync_channel_write_features_V_21_loc_channel = ((features_V_21_loc_channel_full_n & ap_channel_done_features_V_21_loc_channel) | ap_sync_reg_channel_write_features_V_21_loc_channel);

assign ap_sync_channel_write_features_V_22_loc_channel = ((features_V_22_loc_channel_full_n & ap_channel_done_features_V_22_loc_channel) | ap_sync_reg_channel_write_features_V_22_loc_channel);

assign ap_sync_channel_write_features_V_23_loc_channel = ((features_V_23_loc_channel_full_n & ap_channel_done_features_V_23_loc_channel) | ap_sync_reg_channel_write_features_V_23_loc_channel);

assign ap_sync_channel_write_features_V_24_loc_channel = ((features_V_24_loc_channel_full_n & ap_channel_done_features_V_24_loc_channel) | ap_sync_reg_channel_write_features_V_24_loc_channel);

assign ap_sync_channel_write_features_V_25_loc_channel = ((features_V_25_loc_channel_full_n & ap_channel_done_features_V_25_loc_channel) | ap_sync_reg_channel_write_features_V_25_loc_channel);

assign ap_sync_channel_write_features_V_26_loc_channel = ((features_V_26_loc_channel_full_n & ap_channel_done_features_V_26_loc_channel) | ap_sync_reg_channel_write_features_V_26_loc_channel);

assign ap_sync_channel_write_features_V_27_loc_channel = ((features_V_27_loc_channel_full_n & ap_channel_done_features_V_27_loc_channel) | ap_sync_reg_channel_write_features_V_27_loc_channel);

assign ap_sync_channel_write_features_V_28_loc_channel = ((features_V_28_loc_channel_full_n & ap_channel_done_features_V_28_loc_channel) | ap_sync_reg_channel_write_features_V_28_loc_channel);

assign ap_sync_channel_write_features_V_29_loc_channel = ((features_V_29_loc_channel_full_n & ap_channel_done_features_V_29_loc_channel) | ap_sync_reg_channel_write_features_V_29_loc_channel);

assign ap_sync_channel_write_features_V_2_loc_channel = ((features_V_2_loc_channel_full_n & ap_channel_done_features_V_2_loc_channel) | ap_sync_reg_channel_write_features_V_2_loc_channel);

assign ap_sync_channel_write_features_V_30_loc_channel = ((features_V_30_loc_channel_full_n & ap_channel_done_features_V_30_loc_channel) | ap_sync_reg_channel_write_features_V_30_loc_channel);

assign ap_sync_channel_write_features_V_31_loc_channel = ((features_V_31_loc_channel_full_n & ap_channel_done_features_V_31_loc_channel) | ap_sync_reg_channel_write_features_V_31_loc_channel);

assign ap_sync_channel_write_features_V_3_loc_channel = ((features_V_3_loc_channel_full_n & ap_channel_done_features_V_3_loc_channel) | ap_sync_reg_channel_write_features_V_3_loc_channel);

assign ap_sync_channel_write_features_V_4_loc_channel = ((features_V_4_loc_channel_full_n & ap_channel_done_features_V_4_loc_channel) | ap_sync_reg_channel_write_features_V_4_loc_channel);

assign ap_sync_channel_write_features_V_5_loc_channel = ((features_V_5_loc_channel_full_n & ap_channel_done_features_V_5_loc_channel) | ap_sync_reg_channel_write_features_V_5_loc_channel);

assign ap_sync_channel_write_features_V_6_loc_channel = ((features_V_6_loc_channel_full_n & ap_channel_done_features_V_6_loc_channel) | ap_sync_reg_channel_write_features_V_6_loc_channel);

assign ap_sync_channel_write_features_V_7_loc_channel = ((features_V_7_loc_channel_full_n & ap_channel_done_features_V_7_loc_channel) | ap_sync_reg_channel_write_features_V_7_loc_channel);

assign ap_sync_channel_write_features_V_8_loc_channel = ((features_V_8_loc_channel_full_n & ap_channel_done_features_V_8_loc_channel) | ap_sync_reg_channel_write_features_V_8_loc_channel);

assign ap_sync_channel_write_features_V_9_loc_channel = ((features_V_9_loc_channel_full_n & ap_channel_done_features_V_9_loc_channel) | ap_sync_reg_channel_write_features_V_9_loc_channel);

assign ap_sync_channel_write_features_V_loc_channel = ((features_V_loc_channel_full_n & ap_channel_done_features_V_loc_channel) | ap_sync_reg_channel_write_features_V_loc_channel);

assign ap_sync_ready = (ap_sync_Loop_read_input_features_proc2_U0_ap_ready & ap_sync_Block_logistic_regression_for_cond_i_exit_proc_U0_ap_ready);

assign in_stream_TREADY = Loop_read_input_features_proc2_U0_in_stream_TREADY;

assign out_stream_TDATA = Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TDATA;

assign out_stream_TKEEP = Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TKEEP;

assign out_stream_TLAST = Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TLAST;

assign out_stream_TSTRB = Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TSTRB;

assign out_stream_TVALID = Block_logistic_regression_for_cond_i_exit_proc_U0_out_stream_TVALID;

assign weights_Addr_A = Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Addr_A;

assign weights_Addr_B = Block_logistic_regression_for_cond_i_exit_proc_U0_weights_Addr_B;

assign weights_Clk_A = ap_clk;

assign weights_Clk_B = ap_clk;

assign weights_Din_A = 16'd0;

assign weights_Din_B = 16'd0;

assign weights_EN_A = Block_logistic_regression_for_cond_i_exit_proc_U0_weights_EN_A;

assign weights_EN_B = Block_logistic_regression_for_cond_i_exit_proc_U0_weights_EN_B;

assign weights_Rst_A = ap_rst_n_inv;

assign weights_Rst_B = ap_rst_n_inv;

assign weights_WEN_A = 1'b0;

assign weights_WEN_B = 1'b0;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "logistic_regression_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "logistic_regression_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //logistic_regression

